//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WCFCashHomeDesktopView.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PegarClientePorEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertRecebimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRecebimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRecebimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarRecebimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback pegarRecebimentoPorDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertContaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateContaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarContaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDespesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertDespesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDespesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDespesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDespesaPorDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback AbrirConexãoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::WCFCashHomeDesktopView.Properties.Settings.Default.WCFCashHomeDesktopView_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertClientCompletedEventHandler InsertClientCompleted;
        
        /// <remarks/>
        public event UpdateClientCompletedEventHandler UpdateClientCompleted;
        
        /// <remarks/>
        public event ListarClientesCompletedEventHandler ListarClientesCompleted;
        
        /// <remarks/>
        public event PegarClientePorEmailCompletedEventHandler PegarClientePorEmailCompleted;
        
        /// <remarks/>
        public event InsertRecebimentoCompletedEventHandler InsertRecebimentoCompleted;
        
        /// <remarks/>
        public event UpdateRecebimentoCompletedEventHandler UpdateRecebimentoCompleted;
        
        /// <remarks/>
        public event DeleteRecebimentoCompletedEventHandler DeleteRecebimentoCompleted;
        
        /// <remarks/>
        public event ListarRecebimentoCompletedEventHandler ListarRecebimentoCompleted;
        
        /// <remarks/>
        public event pegarRecebimentoPorDataCompletedEventHandler pegarRecebimentoPorDataCompleted;
        
        /// <remarks/>
        public event InsertContaCompletedEventHandler InsertContaCompleted;
        
        /// <remarks/>
        public event UpdateContaCompletedEventHandler UpdateContaCompleted;
        
        /// <remarks/>
        public event ListarContaCompletedEventHandler ListarContaCompleted;
        
        /// <remarks/>
        public event ListarDespesaCompletedEventHandler ListarDespesaCompleted;
        
        /// <remarks/>
        public event InsertDespesaCompletedEventHandler InsertDespesaCompleted;
        
        /// <remarks/>
        public event UpdateDespesaCompletedEventHandler UpdateDespesaCompleted;
        
        /// <remarks/>
        public event DeleteDespesaCompletedEventHandler DeleteDespesaCompleted;
        
        /// <remarks/>
        public event ListarDespesaPorDataCompletedEventHandler ListarDespesaPorDataCompleted;
        
        /// <remarks/>
        public event AbrirConexãoCompletedEventHandler AbrirConexãoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsertClient([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente cliente) {
            object[] results = this.Invoke("InsertClient", new object[] {
                        cliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertClientAsync(Cliente cliente) {
            this.InsertClientAsync(cliente, null);
        }
        
        /// <remarks/>
        public void InsertClientAsync(Cliente cliente, object userState) {
            if ((this.InsertClientOperationCompleted == null)) {
                this.InsertClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertClientOperationCompleted);
            }
            this.InvokeAsync("InsertClient", new object[] {
                        cliente}, this.InsertClientOperationCompleted, userState);
        }
        
        private void OnInsertClientOperationCompleted(object arg) {
            if ((this.InsertClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertClientCompleted(this, new InsertClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdateClient([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente cliente) {
            object[] results = this.Invoke("UpdateClient", new object[] {
                        cliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateClientAsync(Cliente cliente) {
            this.UpdateClientAsync(cliente, null);
        }
        
        /// <remarks/>
        public void UpdateClientAsync(Cliente cliente, object userState) {
            if ((this.UpdateClientOperationCompleted == null)) {
                this.UpdateClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateClientOperationCompleted);
            }
            this.InvokeAsync("UpdateClient", new object[] {
                        cliente}, this.UpdateClientOperationCompleted, userState);
        }
        
        private void OnUpdateClientOperationCompleted(object arg) {
            if ((this.UpdateClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateClientCompleted(this, new UpdateClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
        public Cliente[] ListarClientes() {
            object[] results = this.Invoke("ListarClientes", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClientesAsync() {
            this.ListarClientesAsync(null);
        }
        
        /// <remarks/>
        public void ListarClientesAsync(object userState) {
            if ((this.ListarClientesOperationCompleted == null)) {
                this.ListarClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClientesOperationCompleted);
            }
            this.InvokeAsync("ListarClientes", new object[0], this.ListarClientesOperationCompleted, userState);
        }
        
        private void OnListarClientesOperationCompleted(object arg) {
            if ((this.ListarClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClientesCompleted(this, new ListarClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PegarClientePorEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cliente PegarClientePorEmail([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email) {
            object[] results = this.Invoke("PegarClientePorEmail", new object[] {
                        email});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void PegarClientePorEmailAsync(string email) {
            this.PegarClientePorEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void PegarClientePorEmailAsync(string email, object userState) {
            if ((this.PegarClientePorEmailOperationCompleted == null)) {
                this.PegarClientePorEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPegarClientePorEmailOperationCompleted);
            }
            this.InvokeAsync("PegarClientePorEmail", new object[] {
                        email}, this.PegarClientePorEmailOperationCompleted, userState);
        }
        
        private void OnPegarClientePorEmailOperationCompleted(object arg) {
            if ((this.PegarClientePorEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PegarClientePorEmailCompleted(this, new PegarClientePorEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertRecebimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsertRecebimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Recebimento recebimento) {
            object[] results = this.Invoke("InsertRecebimento", new object[] {
                        recebimento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertRecebimentoAsync(Recebimento recebimento) {
            this.InsertRecebimentoAsync(recebimento, null);
        }
        
        /// <remarks/>
        public void InsertRecebimentoAsync(Recebimento recebimento, object userState) {
            if ((this.InsertRecebimentoOperationCompleted == null)) {
                this.InsertRecebimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertRecebimentoOperationCompleted);
            }
            this.InvokeAsync("InsertRecebimento", new object[] {
                        recebimento}, this.InsertRecebimentoOperationCompleted, userState);
        }
        
        private void OnInsertRecebimentoOperationCompleted(object arg) {
            if ((this.InsertRecebimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertRecebimentoCompleted(this, new InsertRecebimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateRecebimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdateRecebimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Recebimento recebimento) {
            object[] results = this.Invoke("UpdateRecebimento", new object[] {
                        recebimento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRecebimentoAsync(Recebimento recebimento) {
            this.UpdateRecebimentoAsync(recebimento, null);
        }
        
        /// <remarks/>
        public void UpdateRecebimentoAsync(Recebimento recebimento, object userState) {
            if ((this.UpdateRecebimentoOperationCompleted == null)) {
                this.UpdateRecebimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRecebimentoOperationCompleted);
            }
            this.InvokeAsync("UpdateRecebimento", new object[] {
                        recebimento}, this.UpdateRecebimentoOperationCompleted, userState);
        }
        
        private void OnUpdateRecebimentoOperationCompleted(object arg) {
            if ((this.UpdateRecebimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRecebimentoCompleted(this, new UpdateRecebimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteRecebimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeleteRecebimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Recebimento recebimento) {
            object[] results = this.Invoke("DeleteRecebimento", new object[] {
                        recebimento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRecebimentoAsync(Recebimento recebimento) {
            this.DeleteRecebimentoAsync(recebimento, null);
        }
        
        /// <remarks/>
        public void DeleteRecebimentoAsync(Recebimento recebimento, object userState) {
            if ((this.DeleteRecebimentoOperationCompleted == null)) {
                this.DeleteRecebimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRecebimentoOperationCompleted);
            }
            this.InvokeAsync("DeleteRecebimento", new object[] {
                        recebimento}, this.DeleteRecebimentoOperationCompleted, userState);
        }
        
        private void OnDeleteRecebimentoOperationCompleted(object arg) {
            if ((this.DeleteRecebimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRecebimentoCompleted(this, new DeleteRecebimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarRecebimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
        public Recebimento[] ListarRecebimento() {
            object[] results = this.Invoke("ListarRecebimento", new object[0]);
            return ((Recebimento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarRecebimentoAsync() {
            this.ListarRecebimentoAsync(null);
        }
        
        /// <remarks/>
        public void ListarRecebimentoAsync(object userState) {
            if ((this.ListarRecebimentoOperationCompleted == null)) {
                this.ListarRecebimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarRecebimentoOperationCompleted);
            }
            this.InvokeAsync("ListarRecebimento", new object[0], this.ListarRecebimentoOperationCompleted, userState);
        }
        
        private void OnListarRecebimentoOperationCompleted(object arg) {
            if ((this.ListarRecebimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarRecebimentoCompleted(this, new ListarRecebimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/pegarRecebimentoPorData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
        public Recebimento[] pegarRecebimentoPorData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mes, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailLogado) {
            object[] results = this.Invoke("pegarRecebimentoPorData", new object[] {
                        mes,
                        emailLogado});
            return ((Recebimento[])(results[0]));
        }
        
        /// <remarks/>
        public void pegarRecebimentoPorDataAsync(string mes, string emailLogado) {
            this.pegarRecebimentoPorDataAsync(mes, emailLogado, null);
        }
        
        /// <remarks/>
        public void pegarRecebimentoPorDataAsync(string mes, string emailLogado, object userState) {
            if ((this.pegarRecebimentoPorDataOperationCompleted == null)) {
                this.pegarRecebimentoPorDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpegarRecebimentoPorDataOperationCompleted);
            }
            this.InvokeAsync("pegarRecebimentoPorData", new object[] {
                        mes,
                        emailLogado}, this.pegarRecebimentoPorDataOperationCompleted, userState);
        }
        
        private void OnpegarRecebimentoPorDataOperationCompleted(object arg) {
            if ((this.pegarRecebimentoPorDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pegarRecebimentoPorDataCompleted(this, new pegarRecebimentoPorDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertConta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsertConta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Conta cliente) {
            object[] results = this.Invoke("InsertConta", new object[] {
                        cliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertContaAsync(Conta cliente) {
            this.InsertContaAsync(cliente, null);
        }
        
        /// <remarks/>
        public void InsertContaAsync(Conta cliente, object userState) {
            if ((this.InsertContaOperationCompleted == null)) {
                this.InsertContaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertContaOperationCompleted);
            }
            this.InvokeAsync("InsertConta", new object[] {
                        cliente}, this.InsertContaOperationCompleted, userState);
        }
        
        private void OnInsertContaOperationCompleted(object arg) {
            if ((this.InsertContaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertContaCompleted(this, new InsertContaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateConta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdateConta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Conta conta) {
            object[] results = this.Invoke("UpdateConta", new object[] {
                        conta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateContaAsync(Conta conta) {
            this.UpdateContaAsync(conta, null);
        }
        
        /// <remarks/>
        public void UpdateContaAsync(Conta conta, object userState) {
            if ((this.UpdateContaOperationCompleted == null)) {
                this.UpdateContaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateContaOperationCompleted);
            }
            this.InvokeAsync("UpdateConta", new object[] {
                        conta}, this.UpdateContaOperationCompleted, userState);
        }
        
        private void OnUpdateContaOperationCompleted(object arg) {
            if ((this.UpdateContaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateContaCompleted(this, new UpdateContaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarConta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
        public Conta[] ListarConta() {
            object[] results = this.Invoke("ListarConta", new object[0]);
            return ((Conta[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarContaAsync() {
            this.ListarContaAsync(null);
        }
        
        /// <remarks/>
        public void ListarContaAsync(object userState) {
            if ((this.ListarContaOperationCompleted == null)) {
                this.ListarContaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarContaOperationCompleted);
            }
            this.InvokeAsync("ListarConta", new object[0], this.ListarContaOperationCompleted, userState);
        }
        
        private void OnListarContaOperationCompleted(object arg) {
            if ((this.ListarContaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarContaCompleted(this, new ListarContaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarDespesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
        public Despesas[] ListarDespesa() {
            object[] results = this.Invoke("ListarDespesa", new object[0]);
            return ((Despesas[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarDespesaAsync() {
            this.ListarDespesaAsync(null);
        }
        
        /// <remarks/>
        public void ListarDespesaAsync(object userState) {
            if ((this.ListarDespesaOperationCompleted == null)) {
                this.ListarDespesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDespesaOperationCompleted);
            }
            this.InvokeAsync("ListarDespesa", new object[0], this.ListarDespesaOperationCompleted, userState);
        }
        
        private void OnListarDespesaOperationCompleted(object arg) {
            if ((this.ListarDespesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDespesaCompleted(this, new ListarDespesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertDespesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsertDespesa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Despesas despesa) {
            object[] results = this.Invoke("InsertDespesa", new object[] {
                        despesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertDespesaAsync(Despesas despesa) {
            this.InsertDespesaAsync(despesa, null);
        }
        
        /// <remarks/>
        public void InsertDespesaAsync(Despesas despesa, object userState) {
            if ((this.InsertDespesaOperationCompleted == null)) {
                this.InsertDespesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertDespesaOperationCompleted);
            }
            this.InvokeAsync("InsertDespesa", new object[] {
                        despesa}, this.InsertDespesaOperationCompleted, userState);
        }
        
        private void OnInsertDespesaOperationCompleted(object arg) {
            if ((this.InsertDespesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertDespesaCompleted(this, new InsertDespesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateDespesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdateDespesa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Despesas despesa) {
            object[] results = this.Invoke("UpdateDespesa", new object[] {
                        despesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDespesaAsync(Despesas despesa) {
            this.UpdateDespesaAsync(despesa, null);
        }
        
        /// <remarks/>
        public void UpdateDespesaAsync(Despesas despesa, object userState) {
            if ((this.UpdateDespesaOperationCompleted == null)) {
                this.UpdateDespesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDespesaOperationCompleted);
            }
            this.InvokeAsync("UpdateDespesa", new object[] {
                        despesa}, this.UpdateDespesaOperationCompleted, userState);
        }
        
        private void OnUpdateDespesaOperationCompleted(object arg) {
            if ((this.UpdateDespesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDespesaCompleted(this, new UpdateDespesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteDespesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeleteDespesa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Despesas despesa) {
            object[] results = this.Invoke("DeleteDespesa", new object[] {
                        despesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteDespesaAsync(Despesas despesa) {
            this.DeleteDespesaAsync(despesa, null);
        }
        
        /// <remarks/>
        public void DeleteDespesaAsync(Despesas despesa, object userState) {
            if ((this.DeleteDespesaOperationCompleted == null)) {
                this.DeleteDespesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDespesaOperationCompleted);
            }
            this.InvokeAsync("DeleteDespesa", new object[] {
                        despesa}, this.DeleteDespesaOperationCompleted, userState);
        }
        
        private void OnDeleteDespesaOperationCompleted(object arg) {
            if ((this.DeleteDespesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDespesaCompleted(this, new DeleteDespesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarDespesaPorData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
        public Despesas[] ListarDespesaPorData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mes, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rmailLogado) {
            object[] results = this.Invoke("ListarDespesaPorData", new object[] {
                        mes,
                        rmailLogado});
            return ((Despesas[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarDespesaPorDataAsync(string mes, string rmailLogado) {
            this.ListarDespesaPorDataAsync(mes, rmailLogado, null);
        }
        
        /// <remarks/>
        public void ListarDespesaPorDataAsync(string mes, string rmailLogado, object userState) {
            if ((this.ListarDespesaPorDataOperationCompleted == null)) {
                this.ListarDespesaPorDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDespesaPorDataOperationCompleted);
            }
            this.InvokeAsync("ListarDespesaPorData", new object[] {
                        mes,
                        rmailLogado}, this.ListarDespesaPorDataOperationCompleted, userState);
        }
        
        private void OnListarDespesaPorDataOperationCompleted(object arg) {
            if ((this.ListarDespesaPorDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDespesaPorDataCompleted(this, new ListarDespesaPorDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AbrirConexão", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbrirConexão() {
            object[] results = this.Invoke("AbrirConexão", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AbrirConexãoAsync() {
            this.AbrirConexãoAsync(null);
        }
        
        /// <remarks/>
        public void AbrirConexãoAsync(object userState) {
            if ((this.AbrirConexãoOperationCompleted == null)) {
                this.AbrirConexãoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAbrirConexãoOperationCompleted);
            }
            this.InvokeAsync("AbrirConexão", new object[0], this.AbrirConexãoOperationCompleted, userState);
        }
        
        private void OnAbrirConexãoOperationCompleted(object arg) {
            if ((this.AbrirConexãoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AbrirConexãoCompleted(this, new AbrirConexãoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
    public partial class Cliente {
        
        private string cpfField;
        
        private string dataNascimentoField;
        
        private string emailField;
        
        private int idField;
        
        private string nomeField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
    public partial class Despesas {
        
        private string categoriaField;
        
        private string dataEmissaoField;
        
        private string descricaoField;
        
        private string emailClienteField;
        
        private int idDespesaField;
        
        private int statusField;
        
        private float valorDespesaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmailCliente {
            get {
                return this.emailClienteField;
            }
            set {
                this.emailClienteField = value;
            }
        }
        
        /// <remarks/>
        public int IdDespesa {
            get {
                return this.idDespesaField;
            }
            set {
                this.idDespesaField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public float ValorDespesa {
            get {
                return this.valorDespesaField;
            }
            set {
                this.valorDespesaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
    public partial class Conta {
        
        private string emailClienteField;
        
        private float salarioContaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmailCliente {
            get {
                return this.emailClienteField;
            }
            set {
                this.emailClienteField = value;
            }
        }
        
        /// <remarks/>
        public float SalarioConta {
            get {
                return this.salarioContaField;
            }
            set {
                this.salarioContaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.model")]
    public partial class Recebimento {
        
        private string categoriaField;
        
        private string dataRecebimentoField;
        
        private string descricaoField;
        
        private string emailRecebimentoField;
        
        private int idRecebimentoField;
        
        private int statusField;
        
        private float valorRecebimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataRecebimento {
            get {
                return this.dataRecebimentoField;
            }
            set {
                this.dataRecebimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmailRecebimento {
            get {
                return this.emailRecebimentoField;
            }
            set {
                this.emailRecebimentoField = value;
            }
        }
        
        /// <remarks/>
        public int IdRecebimento {
            get {
                return this.idRecebimentoField;
            }
            set {
                this.idRecebimentoField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public float ValorRecebimento {
            get {
                return this.valorRecebimentoField;
            }
            set {
                this.valorRecebimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertClientCompletedEventHandler(object sender, InsertClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateClientCompletedEventHandler(object sender, UpdateClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarClientesCompletedEventHandler(object sender, ListarClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PegarClientePorEmailCompletedEventHandler(object sender, PegarClientePorEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PegarClientePorEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PegarClientePorEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertRecebimentoCompletedEventHandler(object sender, InsertRecebimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertRecebimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertRecebimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateRecebimentoCompletedEventHandler(object sender, UpdateRecebimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRecebimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRecebimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteRecebimentoCompletedEventHandler(object sender, DeleteRecebimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRecebimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRecebimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarRecebimentoCompletedEventHandler(object sender, ListarRecebimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarRecebimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarRecebimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Recebimento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Recebimento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void pegarRecebimentoPorDataCompletedEventHandler(object sender, pegarRecebimentoPorDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pegarRecebimentoPorDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pegarRecebimentoPorDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Recebimento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Recebimento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertContaCompletedEventHandler(object sender, InsertContaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertContaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertContaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateContaCompletedEventHandler(object sender, UpdateContaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateContaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateContaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarContaCompletedEventHandler(object sender, ListarContaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarContaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarContaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Conta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Conta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarDespesaCompletedEventHandler(object sender, ListarDespesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDespesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDespesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Despesas[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Despesas[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertDespesaCompletedEventHandler(object sender, InsertDespesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertDespesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertDespesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateDespesaCompletedEventHandler(object sender, UpdateDespesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDespesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDespesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteDespesaCompletedEventHandler(object sender, DeleteDespesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteDespesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteDespesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarDespesaPorDataCompletedEventHandler(object sender, ListarDespesaPorDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDespesaPorDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDespesaPorDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Despesas[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Despesas[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AbrirConexãoCompletedEventHandler(object sender, AbrirConexãoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbrirConexãoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AbrirConexãoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591